require("josean.core.options")
require("josean.core.keymaps.buffer")
require("josean.core.keymaps.global")
require("josean.scripts.plugins.ports").start(3000)
require("josean.scripts.plugins.playwright-runner")
require("josean.scripts.plugins.jest-runner")
